=== RicardoRomao/iselsd/trunk/Trabalho 3/BlockBuster/CinemaModel/Showtime.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Ricardo Neto (Netpat) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- Definição do tipo que representa uma sala de cinema -->
	<xs:complexType name="t_room">
		<xs:attribute name="id" type="xs:integer"/>
		<xs:attribute name="capacity" type="xs:integer"/>
	</xs:complexType>
	<!-- Definição do tipo que representa um contentor de salas -->
	<xs:complexType name="t_rooms">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="room" type="t_room"/>
		</xs:sequence>
	</xs:complexType>
	<!-- Definição do tipo que representa um filme -->
	<xs:complexType name="t_movie">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:integer"/>
				<xs:attribute name="title" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!-- Definição do tipo que representa um contentor de filmes -->
	<xs:complexType name="t_movies">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="movie" type="t_movie"/>
		</xs:sequence>
	</xs:complexType>
	<!-- Definição do tipo que representa uma sessão -->
	<xs:complexType name="t_session">
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="startTime" type="xs:time"/>
		<xs:attribute name="movieId" type="xs:int"/>
		<xs:attribute name="roomId" type="xs:int"/>
	</xs:complexType>
	<!-- Definição do tipo que representa um contentor de sessões -->
	<xs:complexType name="t_sessions">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="session" type="t_session">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!-- Definição do root element -->
	<xs:element name="contents">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="rooms" type="t_rooms" minOccurs="1" maxOccurs="1">
					<xs:unique name="un_roomId">
						<xs:selector xpath="*"/>
						<xs:field xpath="@id"/>
					</xs:unique>
				</xs:element>
				<xs:element name="movies" type="t_movies" minOccurs="1" maxOccurs="1">
					<xs:unique name="un_movieId">
						<xs:selector xpath="*"/>
						<xs:field xpath="@id"/>
					</xs:unique>
				</xs:element>
				<xs:element name="sessions" type="t_sessions" minOccurs="1" maxOccurs="1">
					<xs:unique name="un_sessionId">
						<xs:selector xpath="*"/>
						<xs:field xpath="@id"/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="pk_room">
			<xs:selector xpath="rooms/room"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="pk_movie">
			<xs:selector xpath="movies/movie"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:keyref refer="pk_movie" name="fk_movie">
			<xs:selector xpath="sessions/session"/>
			<xs:field xpath="@movieId"/>
		</xs:keyref>
		<xs:keyref refer="pk_room" name="fk_room">
			<xs:selector xpath="sessions/session"/>
			<xs:field xpath="@roomId"/>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== RicardoRomao/iselsd/trunk/Trabalho 3/BlockBuster/CinemaModel/Showtime - BBC.xml
<?xml version="1.0" encoding="utf-8"?>
<contents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Showtime.xsd">
	<rooms>
		<room id="1" capacity="10"/>
		<room id="2" capacity="20"/>
		<room id="3" capacity="30"/>
	</rooms>
	<movies>
		<movie id="1" title="A Ilha de Impy">
		  Titiwoo é uma pequena ilha vulcânica no meio do oceano. É aqui que o, pretenso homem da Renascença, zoólogo e cientista indisciplinado, Professor Horatio Tiberton vive e trabalha. Juntamente com o filho adoptado do professor, Tim, um ilustre bando de criaturas da ilha assiste à escola idiossincrásica de línguas de Tibberton: Ping, o pinguim; Monty, o lagarto monitor; Shoe, o pássaro e Solomon, o elefante-marinho. A dona da casa e da escola de Tibberton é Peg, a senhora-porca. A vida é feliz para todos os habitantes da ilha. Até que, um dia, um iceberg que tem lá dentro ovos pré-históricos congelados dá à costa e, dos ovos emerge uma estranha criatura verde: é Impy, um dinossauro da idade do gelo. A partir deste momento, a pacata vida dos habitantes da ilha acaba. Quando as novidades sobre Impy chegam ao Rei Pumponnel, que baniu Tibberton para os Mares do Sul, ele faz-se à vela imediatamente, determinado a caçar Impy e adicioná-lo à sua colecção de troféus. Mas Pumponell não conta com os habitantes e as criaturas de Titiwoo. É nessa altura que começa uma perigosa caçada, na qual o grupo de amigos de Tibberton luta para salvar Impy da mira de Pumponell a qualquer custo.
		</movie>
		<movie id="2" title="Como Treinares o Teu Dragão">
		  "Como Treinares o Teu Dragão" passa-se num mundo cheio de Vikings musculados e dragões selvagens. Um adolescente esquelético e desajeitado, filho de Viking, decide matar um dragão para se tornar um herói, provando o seu valor à tribo e ao pai. Mas quando ele se torna amigo do dragão o seu mundo vira-se de cabeça para baixo.
		</movie>
		<movie id="3" title="A Princesa e o Sapo">
		  Uma comédia passada na cidade de Nova Orleães, dos criadores da "A Pequena Sereia" e "Aladin", que é uma versão moderna de um conto clássico, que conta com uma rapariga chamada Tiana, um príncipe sapo que tenta desesperadamente voltar a ser humano e um beijo fatídico que os levará numa hilariante aventura através dos fascinantes riachos do Louisiana.
		</movie>
	</movies>
	<sessions>
		<session id="14H-R1" startTime="14:00:00" movieId="1" roomId="1"/>
		<session id="14H-R2" startTime="14:30:00" movieId="2" roomId="2"/>
		<session id="14H-R3" startTime="14:45:00" movieId="3" roomId="3"/>
		<session id="16H-R1" startTime="16:30:00" movieId="1" roomId="1"/>
		<session id="16H-R2" startTime="16:45:00" movieId="2" roomId="2"/>
		<session id="16H-R3" startTime="16:50:00" movieId="3" roomId="3"/>
		<session id="19H-R1" startTime="19:00:00" movieId="3" roomId="1"/>
		<session id="19H-R2" startTime="19:00:00" movieId="3" roomId="2"/>
		<session id="19H-R3" startTime="19:00:00" movieId="3" roomId="3"/>
	</sessions>
</contents>

=== RicardoRomao/iselsd/Trabalho 3/BlockBuster/CinemaModel/Showtime - BBS.xml
<?xml version="1.0" encoding="utf-8"?>
<contents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Showtime.xsd">
	<rooms>
		<room id="1" capacity="40"/>
		<room id="2" capacity="60"/>
		<room id="3" capacity="120"/>
	</rooms>
	<movies>
		<movie id="1" title="Pesadelo em Elm Street">
		  O maior clássico de terror de todos os tempos, está de volta. Mas desta vez é o actor Jackie Earle Haley quem encarna a mítica personagem de chapéu e garras afiadas, Freddy Krueger. A nova história anda à volta dos adolescentes perseguidos por Freddy Krueger, o assassino horrivelmente desfigurado que os aterroriza durante os sonhos.
		</movie>
		<movie id="2" title="A Era dos Ignorantes">
		  Jean-Marc Leblanc (Marc Labrèche) é um homem com uma vida insignificante, desprezado por todos que, sempre que pode, foge da realidade para uma vida cheia de coisas excitantes. Mas estas, infelizmente, apenas existem na sua imaginação. Nos seus sonhos ele é um cavaleiro, uma estrela de rock, um actor de cinema, um escritor célebre. E sempre com um imenso poder sobre o sexo oposto. Um dia, farto de viver uma existência adulterada, decide mudar de atitude e dar uma nova hipótese à sua vida real.
		</movie>
		<movie id="3" title="Ex-Mulher Procura-se">
		  Milo Boyd é um bounty hunter, ou seja, tem como profissão capturar fugitivos à lei em troca de uma recompensa monetária. Um dia, a sua missão é encontrar e prender a repórter Nicole Hurley, a sua ex-mulher... Quando ele pensava que não haveria tarefa mais fácil, Nicole diz-lhe que está a seguir um importante caso de homicídio, e então Milo percebe que as coisas não vão ser bem como ele tinha planeado. A relação de ambos continua na mesma, até ao momento em que têm de se unir se quiserem viver...
		</movie>
	</movies>
	<sessions>
		<session id="01H-R1" startTime="01:00:00" movieId="1" roomId="1"/>
		<session id="01H-R2" startTime="01:30:00" movieId="2" roomId="2"/>
		<session id="01H-R3" startTime="01:45:00" movieId="3" roomId="3"/>
		<session id="03H-R1" startTime="03:30:00" movieId="1" roomId="1"/>
		<session id="03H-R2" startTime="03:45:00" movieId="2" roomId="2"/>
		<session id="03H-R3" startTime="03:50:00" movieId="3" roomId="3"/>
		<session id="05H-R1" startTime="05:00:00" movieId="2" roomId="1"/>
		<session id="05H-R2" startTime="05:00:00" movieId="3" roomId="2"/>
		<session id="05H-R3" startTime="05:00:00" movieId="3" roomId="3"/>
	</sessions>
</contents>

=== RicardoRomao/iselsd/Trabalho 3/BlockBuster/CinemaModel/Showtime - BBZ.xml
<?xml version="1.0" encoding="utf-8"?>
<contents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Showtime.xsd">
	<rooms>
		<room id="1" capacity="4"/>
		<room id="2" capacity="5"/>
		<room id="3" capacity="6"/>
	</rooms>
	<movies>
		<movie id="1" title="Astro Boy">
		  Passado no cenário futurista de Metro City, «Astro Boy» é um filme sobre um jovem robot com poderes extraordinários, criado por um cientista. Alimentado pela energia positiva "azul", Astro Boy possui uma força hercúlea, visão raio-x, velocidade inacreditável e capacidade para voar. Numa viagem em busca da aceitação, Astro Boy vai aprender as alegrias e emoções de ser humano e ganhar força para abraçar o seu destino. Quando descobre que os seus amigos e família estão em perigo, Astro Boy reúne todos os seus super poderes e regressa a Metro City, esforçando-se corajosamente para salvar tudo aquilo que é mais precioso para si e, ao mesmo tempo, perceber o que é necessário para ser um herói.
		</movie>
		<movie id="2" title="Um Funeral à Chuva">
		  Um grupo de antigos estudantes universitários reencontra-se na cidade onde havia estudado, devido à morte de um deles. Na obrigação de satisfazer o último desejo deste, o grupo inicia uma jornada de auto-descoberta sobre a essência da amizade verdadeira. Contudo, há dez anos que não se viam...
		</movie>
		<movie id="3" title="Toy Story 1 - Os Rivais">
		  Eles são brinquedos, eles falam – pelo menos quando não há pessoas à sua volta – e estão de volta… Woody, alto e magro, um cowboy de quem todos gostam, e Buzzlightyear, o destemido ranger do espaço. A dupla comicamente dissonante aprende, finalmente, a pôr de lado as suas diferenças, quando o destino os separa do seu dono Andy, e se encontram numa missão hilariante, recheada de aventura, onde a única forma de sobrevivência passa por formar uma incómoda aliança.
		</movie>
	</movies>
	<sessions>
		<session id="11H-R1" startTime="11:00:00" movieId="1" roomId="1"/>
		<session id="11H-R2" startTime="11:30:00" movieId="2" roomId="2"/>
		<session id="11H-R3" startTime="11:45:00" movieId="3" roomId="3"/>
		<session id="13H-R1" startTime="13:30:00" movieId="1" roomId="1"/>
		<session id="13H-R2" startTime="13:45:00" movieId="2" roomId="2"/>
		<session id="13H-R3" startTime="13:50:00" movieId="3" roomId="3"/>
		<session id="15H-R1" startTime="15:00:00" movieId="1" roomId="1"/>
		<session id="15H-R2" startTime="15:00:00" movieId="3" roomId="2"/>
		<session id="15H-R3" startTime="15:00:00" movieId="3" roomId="3"/>
	</sessions>
</contents>
