=== RicardoRomao/iselsd/Trabalho 1/DistributedTrivialPursuit/TriviaModel/data/repSquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by Ricardo Neto (Netpat) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="theme" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="card">
								<xs:complexType>
									<xs:all>
										<xs:element name="question">
											<xs:complexType>
												<xs:attribute name="text" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="answer">
											<xs:complexType>
												<xs:attribute name="text" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" id="name" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="theme_name">
			<xs:selector xpath="theme"></xs:selector>
			<xs:field xpath="@name"></xs:field>
		</xs:unique>
	</xs:element>
</xs:schema>

=== RicardoRomao/iselsd/Trabalho 1/DistributedTrivialPursuit/TriviaModel/data/Desporto.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repSquema.xsd">
	<theme name="Desporto">
		<card>
			<question text="O que e que nao se faz sem ovos?"/>
			<answer text="Omelete"/>
		</card>
		<card>
			<question text="Que equipa inglesa de futebol esteve envolvida na tragedia do estadio de Heysel?"/>
			<answer text="Liverpool"/>
		</card>
		<card>
			<question text="Em que ano se comemorou o primeiro centenario dos Jogos Olimpicos modernos?"/>
			<answer text="1996"/>
		</card>
		<card>
			<question text="No Mundial de futebol de 1996 a selecçao portuguesa alcançou o seu melhor resultado de sempre. Em que lugar ficamos?"/>
			<answer text="3"/>
		</card>
		<card>
			<question text="De que cor e o vinho que se extrai da uva Chardonnay?"/>
			<answer text="Branco"/>
		</card>
		<card>
			<question text="O tradicional Bacalhau a Lagareiro e guisado ou assado?"/>
			<answer text="Assado"/>
		</card>
		<card>
			<question text="Que distancia percorreu Carl Lewis em 9.92 segundos?"/>
			<answer text="100"/>
		</card>
		<card>
			<question text="Em que pais de realizaram os primeiros Jogos Olimpicos apos a I Guerra Mundial?"/>
			<answer text="Belgica"/>
		</card>
		<card>
			<question text="Quantas horas dura o circuito de motos de Le Mans?"/>
			<answer text="24"/>
		</card>
		<card>
			<question text="Qual e o ultimo dia em que se pode ser virgem?"/>
			<answer text="23 De Setembro"/>
		</card>
	</theme>
</root>

=== RicardoRomao/iselsd/trunk/Trabalho 1/DistributedTrivialPursuit/TriviaModel/data/Geografia.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repSquema.xsd">
	<theme name="Geografia">
		<card>
			<question text="Em que vila da Beira Interior nasceu o navegador Pedro Alvares Cabral?"/>
			<answer text="Belmonte"/>
		</card>
		<card>
			<question text="Que rio e maior: o Tejo ou o Sena?"/>
			<answer text="Tejo"/>
		</card>
		<card>
			<question text="No norte de Portugal, como e ainda designada a parte inferior de algumas casas que tem como funçao principal guardar o gado?"/>
			<answer text="Loja"/>
		</card>
		<card>
			<question text="Qual e a capital do Iemen?"/>
			<answer text="Sanaa"/>
		</card>
		<card>
			<question text="Boticas, a localidade onde se situa a estancia de aguas minerais Carvalhelhos, pertence a que distrito?"/>
			<answer text="Vila Real"/>
		</card>
		<card>
			<question text="Que pedra preciosa da nome a uma regiao da Sardenha?"/>
			<answer text="Esmeralda"/>
		</card>
		<card>
			<question text="A que pais pertencem actualmente as ilhas Bounty, descobertas em 1788?"/>
			<answer text="Nova Zelandia"/>
		</card>
		<card>
			<question text="Qual e o oceano mais pequeno do mundo?"/>
			<answer text="Arctico"/>
		</card>
		<card>
			<question text="Qual e a torre mais alta da Europa?"/>
			<answer text="Torre Eiffel"/>
		</card>
		<card>
			<question text="Que pequeno pais faz fronteira com a Alemanha, a Belgica e a França?"/>
			<answer text="Luxemburgo"/>
		</card>
	</theme>
</root>

=== RicardoRomao/iselsd/Trabalho 1/DistributedTrivialPursuit/TriviaModel/data/Ciencias.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repSquema.xsd">
	<theme name="Ciencias">
		<card>
			<question text="O acido acetilsalicilico e componente principal de que vulgar medicamento?"/>
			<answer text="Aspirina"/>
		</card>
		<card>
			<question text="A temperatura global do nosso planeta esta a subir. Quanto aumentou aproximadamente nos ultimos 100 anos?"/>
			<answer text="1"/>
		</card>
		<card>
			<question text="Qual a sigla que os veiculos movidos a gaz tem origatoriamente de usar?"/>
			<answer text="Gpl"/>
		</card>
		<card>
			<question text="Qual e o numero maximo de eclipses que podem ocorrer num ano?"/>
			<answer text="5"/>
		</card>
		<card>
			<question text="Qual e o unico planeta cuja rotaçao e feita no sentido dos ponteiros do relogio?"/>
			<answer text="Venus"/>
		</card>
		<card>
			<question text="Uma caça-minas e um 'navio' ou um 'aviao' de guerra?"/>
			<answer text="Navio"/>
		</card>
		<card>
			<question text="Que planeta tem o ano mais curto?"/>
			<answer text="Mercurio"/>
		</card>
		<card>
			<question text="Que terrivel doença foi identificada pela 1ª vez nos Estados Unidos pelo Prof. Michael Gottlieb?"/>
			<answer text="Sida"/>
		</card>
		<card>
			<question text="Para alem dos seres humanos, que outros animais acasalam de frente um para o outro?"/>
			<answer text="Golfinhos E Baleias"/>
		</card>
		<card>
			<question text="Que faz uma vaca durante o 3/4 dia?"/>
			<answer text="Rumina"/>
		</card>
	</theme>
</root>

=== RicardoRomao/iselsd/trunk/Trabalho 1/DistributedTrivialPursuit/TriviaModel/data/Literatura.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repSquema.xsd">
	<theme name="Literatura">
		<card>
			<question text="O judeu Shylock e o principal personagem de que peça de Shakespeare?"/>
			<answer text="O Mercador De Veneza"/>
		</card>
		<card>
			<question text="Como se chama o pai de carne e osso do infeliz boneco de madeira a quem crescia o nariz quando mentia?"/>
			<answer text="Geppetto"/>
		</card>
		<card>
			<question text="Quem e o cavaleiro da triste figura?"/>
			<answer text="Dom Quixote"/>
		</card>
		<card>
			<question text="Que pintor e escultor italiano morreu no mesmo ano em que nasceu Shakespeare?"/>
			<answer text="Miguel Angelo"/>
		</card>
		<card>
			<question text="De quem estava a espera Vladimir uma famosa obra de Samuel Beckett?"/>
			<answer text="Godot"/>
		</card>
		<card>
			<question text="Em que pais decorre a acçao do ballet Giselle?"/>
			<answer text="Alemanha"/>
		</card>
		<card>
			<question text="Fidelio e a unica opera de que compositor?"/>
			<answer text="Beethoven"/>
		</card>
		<card>
			<question text="De que personagem descreveu as aventuras J. M. Barrie?"/>
			<answer text="Peter Pan"/>
		</card>
		<card>
			<question text="Como se chamava o escritor homossexual que foi o grande amor da pintora Dora Carrington?"/>
			<answer text="Lytton Strachey"/>
		</card>
		<card>
			<question text="Quem e o autor da fabula A Lebre e a Tartaruga?"/>
			<answer text="Esopo"/>
		</card>
	</theme>
</root>

=== RicardoRomao/iselsd/trunk/Trabalho 1/DistributedTrivialPursuit/TriviaModel/data/Cinema.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repSquema.xsd">
	<theme name="Cinema">
		<card>
			<question text="Que grupo punk gostaria que Deus barbeasse a rainha de Inglaterra, fazendo um trocadilho divertido com o hino ingles?"/>
			<answer text="Sex Pistols"/>
		</card>
		<card>
			<question text="Que celebre moinho parisiense festejou o seu primeiro centenario em 1989?"/>
			<answer text="Moulin Rouge"/>
		</card>
		<card>
			<question text="Os U2 inventaram um canal de televisao para apresentarem a sua digressão de 1993. Como se chamava?"/>
			<answer text="Zoo Tv"/>
		</card>
		<card>
			<question text="Que actriz nao resistiu a uma Proposta Indecente?"/>
			<answer text="Demi Moore"/>
		</card>
		<card>
			<question text="Em que loja gostava Audrey Hepburn de tomar o pequeno-almoço no filme Boneca de Luxo?"/>
			<answer text="Tiffany's"/>
		</card>
		<card>
			<question text="O que significa a sigla CNN?"/>
			<answer text="Cable News Network"/>
		</card>
		<card>
			<question text="Como se chama a nave espacial de 2001: Odisseia no Espaço ?"/>
			<answer text="Discovery"/>
		</card>
		<card>
			<question text="Quem dirigiu Claudia Cardinali e Alain Delon em O Leopardo?"/>
			<answer text="Visconti"/>
		</card>
		<card>
			<question text="Como se chama o projecto de benefencia criado por Bob Geldof em 1984?"/>
			<answer text="Live Aid"/>
		</card>
		<card>
			<question text="Quem era o homem das Mil Imagens e, mais tarde, de Chuva de Estrelas?"/>
			<answer text="Jose Nuno Martins"/>
		</card>
	</theme>
</root>

=== RicardoRomao/iselsd/Trabalho 1/DistributedTrivialPursuit/TriviaModel/data/Historia.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repSquema.xsd">
	<theme name="Historia">
		<card>
			<question text="A que presidente norte-americano assasinado sucedeu Andrew Johnson?"/>
			<answer text="Abraham Lincoln"/>
		</card>
		<card>
			<question text="Que rei portugues, conhecido pelo seu mau feitio, obrigou a sua rainha a transformar pao em rosas?"/>
			<answer text="Dinis"/>
		</card>
		<card>
			<question text="Que presidente norte-americano assinou o Tratado de Versalhes no fim da 1º Guerra Mundial?"/>
			<answer text="Woodrow Wilson"/>
		</card>
		<card>
			<question text="Quem tentou Juan Fernandez Krohn assassinar a 13 de Maio de 1981?"/>
			<answer text="Joao Paulo"/>
		</card>
		<card>
			<question text="Foi uma rainha portuguesa que introduziu em Inglaterra o, agora muito british, habito de tomar cha. Quem foi ela?"/>
			<answer text="Catarina"/>
		</card>
		<card>
			<question text="Em que ano aconteceu o desastre nuclear na central russa de Chernobyl?"/>
			<answer text="1986"/>
		</card>
		<card>
			<question text="No inicio desde seculo houve um burçao portugues que foi considerado o mais arrojado falsificador do mundo. De quem se trata?"/>
			<answer text="Alves Dos Reis"/>
		</card>
		<card>
			<question text="O comboio correio, vítima do roubo do seculo efectuado em 1963, viajava entre Londres e que outra cidade britanica?"/>
			<answer text="Glasgow"/>
		</card>
		<card>
			<question text="Em que ano morreu Sir Winston Churchill?"/>
			<answer text="1965"/>
		</card>
		<card>
			<question text="Que polemico muro foi construido em 1969?"/>
			<answer text="Muro De Berlim"/>
		</card>
	</theme>
</root>

=== RicardoRomao/iselsd/trunk/Trabalho 1/DistributedTrivialPursuit/TriviaModel/rep.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repSquema.xsd">
	<theme name="Desporto">
		<card>
			<question text="Qual o melhor clube do mundo?"/>
			<answer text="O melhor do mundo é o Benfica!"/>
		</card>
		<card>
			<question text="Qual o maior clube do mundo?"/>
			<answer text="O maior do mundo é o Benfica!"/>
		</card>
		<card>
			<question text="Quantas rodas tem uma bicicleta?"/>
			<answer text="A bicicleta tem 2 rodas. Uma à frente e outra atrás."/>
		</card>
	</theme>
	<theme name="Tecnologia">
		<card>
			<question text="Qual a melhor forma de evitar error num sistema distribuido?"/>
			<answer text="Nao distribuir"/>
		</card>
	</theme>
</root>
